substitutions:

  shutter_entity_1: "cover.hall_window"
  shutter_entity_2: "cover.living_room_window"
  shutter_entity_3: "cover.hall_window"
  shutter_entity_4: "cover.living_room_window"

  shutter_widget_name_1: "shutter1"
  shutter_widget_name_2: "shutter2"
  shutter_widget_name_3: "shutter3"
  shutter_widget_name_4: "shutter4"


  shutter_label_name_1: "shutter 1"
  shutter_label_name_2: "shutter 2"
  shutter_label_name_3: "shutter 3"
  shutter_label_name_4: "shutter 4"


packages:
  shutter_panel: !include shutter_panel.yaml

  shutter_1: !include
    file: shutter_widget.yaml
    vars:
      shutter_entity: "${shutter_entity_1}"
      shutter_widget_name: "${shutter_widget_name_1}"
      
  shutter_2: !include
    file: shutter_widget.yaml
    vars:
      shutter_entity: "${shutter_entity_2}"
      shutter_widget_name: "${shutter_widget_name_2}"
      
  shutter_3: !include
    file: shutter_widget.yaml
    vars:
      shutter_entity: "${shutter_entity_3}"
      shutter_widget_name: "${shutter_widget_name_3}"

  shutter_4: !include
    file: shutter_widget.yaml
    vars:
      shutter_entity: "${shutter_entity_4}"
      shutter_widget_name: "${shutter_widget_name_4}"

