- file: "fonts/Nunito-SemiBold.ttf"
  id: nunito_16
  size: 16
  bpp: 4
  glyphsets:
    - GF_Latin_Core
    # - GF_Greek_Core
    - GF_Cyrillic_Core
    - GF_Latin_Vietnamese
  glyphs: "²"
  extras:
    - file: "fonts/Jua-Regular.ttf"
      glyphs: [
        "\U0000C774",
        "\U0000B8E8",
        "\U0000B9C8",        
      ]

# - file: "fonts/MPLUSRounded1c-Regular.ttf"
#   id: mplus_16
#   size: 16
#   bpp: 4
#   glyphs: "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMНОПРСТУФХЦЧШЩЪЫЬЭЮЯабвгдеёжзийклмнопрстуфхцчшщъыьэюя .,!?-_:°²³¹"

- file: "fonts/Nunito-SemiBold.ttf"
  id: nunito_18
  size: 18
  bpp: 4
  glyphsets:
    - GF_Latin_Core
    # - GF_Greek_Core
    - GF_Cyrillic_Core
    - GF_Latin_Vietnamese

- file: "fonts/Nunito-SemiBold.ttf"
  id: nunito_20
  size: 20
  bpp: 4
  glyphsets:
    - GF_Latin_Core
    # - GF_Greek_Core
    - GF_Cyrillic_Core
    - GF_Latin_Vietnamese

- file: "fonts/Nunito-SemiBold.ttf"
  id: nunito_24
  size: 24
  bpp: 4
  glyphsets:
    - GF_Latin_Core
    # - GF_Greek_Core
    - GF_Cyrillic_Core
    - GF_Latin_Vietnamese

- file: "fonts/Nunito-SemiBold.ttf"
  id: nunito_30
  size: 30
  bpp: 4
  glyphsets:
    - GF_Latin_Core
    # - GF_Greek_Core
    - GF_Cyrillic_Core
    - GF_Latin_Vietnamese

- file: "fonts/Nunito-SemiBold.ttf"
  id: nunito_32
  size: 32
  bpp: 4
  glyphsets:
    - GF_Latin_Core
    # - GF_Greek_Core
    - GF_Cyrillic_Core
    - GF_Latin_Vietnamese

- file: "fonts/Nunito-SemiBold.ttf"
  id: nunito_36
  size: 36
  bpp: 4
  glyphsets:
    - GF_Latin_Core
    # - GF_Greek_Core
    - GF_Cyrillic_Core
    - GF_Latin_Vietnamese

- file: "fonts/Nunito-SemiBold.ttf"
  id: nunito_48
  size: 48
  bpp: 4
  glyphsets:
    - GF_Latin_Core
    # - GF_Greek_Core
    - GF_Cyrillic_Core
    - GF_Latin_Vietnamese

- file: "fonts/Nunito-SemiBold.ttf"
  id: nunito_64
  size: 64
  bpp: 4
  glyphsets:
    - GF_Latin_Core
    # - GF_Greek_Core
    - GF_Cyrillic_Core
    - GF_Latin_Vietnamese

- file: "fonts/Nunito-SemiBold.ttf"
  id: nunito_72
  size: 72
  bpp: 4
  glyphsets:
    - GF_Latin_Core
    # - GF_Greek_Core
    - GF_Cyrillic_Core
    - GF_Latin_Vietnamese

- file: "fonts/Nunito-SemiBold.ttf"
  id: nunito_84
  size: 84
  bpp: 4
  glyphsets:
    - GF_Latin_Core
    # - GF_Greek_Core
    - GF_Cyrillic_Core
    - GF_Latin_Vietnamese

- file: "fonts/icons_v2.ttf"
  id: icons_24
  size: 24
  bpp: 4
  glyphs: [
    "\U0000e926", # fan
    "\U0000e900", # brightness
    "\U0000e901", # saturation
    "\U0000e925", # thermostat
    "\U0000e93b", # air_conditioner 
    "\U0000e936", # heating
    "\U0000e92e", # lock
    "\U0000e935", # home assistant
    "\U0000e931", # wifi signal from 25% to 1%
    "\U0000e932", # wifi signal from 50% to 25%
    "\U0000e933", # wifi signal from 75% to 50%
    "\U0000e934", # wifi signal from 100% to 75% or disable
  ]

- file: "fonts/icons_v2.ttf"
  id: icons_28
  size: 28
  bpp: 4
  glyphs: [
    "\U0000e902", # exit
    "\U0000e926", # fan
    "\U0000e927", # room_plan
    "\U0000e938", # humidity 
    "\U0000e937", # co2
    "\U0000e93a", # air quality (tvoc)
    "\U0000e939", # temperature 
    "\U0000e92f", # illumination (lux)
  ]

- file: "fonts/icons_v2.ttf"
  id: icons_35
  size: 35
  bpp: 4
  glyphs: [
    "\U0000e902", # exit
    "\U0000e926", # fan
    "\U0000e927", # room_plan
    "\U0000e938", # humidity 
    "\U0000e937", # co2
    "\U0000e93a", # air quality (tvoc)
    "\U0000e939", # temperature 
    "\U0000e92f", # illumination (lux)
  ]

- file: "fonts/icons_v2.ttf"
  id: icons_32
  size: 32
  bpp: 4
  glyphs: [
    "\U0000e91f", # arrow_up
    "\U0000e920", # arrow_down
    "\U0000e91c", # stop
    "\U0000e90e", # volume_off
    "\U0000e90f", # volume_on
    "\U0000e910", # volume_minus
    "\U0000e911", # volume_plus
  ]

- file: "fonts/icons_v2.ttf"
  id: icons_36
  size: 36
  bpp: 4
  glyphs: [
    "\U0000e903", # settings
    "\U0000e904", # info
    "\U0000e905", # devices
    "\U0000e906", # home
    "\U0000e907", # ceiling
    "\U0000e908", # lightbulb
    "\U0000e91a", # swipe
    "\U0000e92e", # lock
  ]

- file: "fonts/icons_v2.ttf"
  id: icons_38
  size: 38
  bpp: 4
  glyphs: [
    "\U0000e909", # power
    "\U0000e90c", # back step
    "\U0000e90d", # forward step
    "\U0000e912", # repeat_all
    "\U0000e913", # repeat_off
    "\U0000e914", # repeat_one
    "\U0000e90a", # play
    "\U0000e90b", # pause
    "\U0000e91c", # stop
    "\U0000e923", # locate
    "\U0000e924", # docked
  ]

- file: "fonts/icons_v2.ttf"
  id: icons_48
  size: 48
  bpp: 4
  glyphs: [
    "\U0000e90a", # play
    "\U0000e90b", # pause
    "\U0000e91f", # arrow_up
    "\U0000e920", # arrow_down
    "\U0000e91c", # stop
    "\U0000e923", # locate
    "\U0000e924", # docked
    "\U0000e93b", # air_conditioner 
    "\U0000e936", # heating
    "\U0000e938", # humidity
    "\U0000e939", # temperature 
  ]

- file: "fonts/icons_v2.ttf"
  id: icons_72
  size: 72
  bpp: 4
  glyphs: [
    "\U0000e91b", # music
    "\U0000e91d", # shutter_close
    "\U0000e922", # vacuum
    "\U0000e925", # thermostat
    "\U0000e93b", # air_conditioner
  ]

- file: "fonts/icons_v2.ttf"
  id: icons_90
  size: 90
  bpp: 4
  glyphs: [
    "\U0000e908", # lightbulb
    "\U0000e915", # spotlights_group
    "\U0000e916", # desk_lamp
    "\U0000e917", # pendant_lamp
    "\U0000e918", # ceiling_lamp
    "\U0000e921", # ceiling_lamp_variant
    "\U0000e919", # night_lamp
    "\U0000e91d", # 0 - shutter_closed
    "\U0000e93d", # 10 - shutter
    "\U0000e93e", # 20 - shutter
    "\U0000e93f", # 30 - shutter
    "\U0000e940", # 40 - shutter
    "\U0000e941", # 50 - shutter
    "\U0000e93c", # 60 - shutter
    "\U0000e943", # 70 - shutter
    "\U0000e944", # 80 - shutter
    "\U0000e942", # 90 - shutter
    "\U0000e91e",  # 100 - shutter_open
    "\U0000e91b", # music
    "\U0000e91f", # arrow_up
    "\U0000e920", # arrow_down
    "\U0000e922", # vacuum
  ]
  


- file: "fonts/icons_v2.ttf"
  id: icons_300
  size: 300
  bpp: 4
  glyphs: [
    "\U0000e91d", # 0 - shutter_closed
    "\U0000e93d", # 10 - shutter
    "\U0000e93e", # 20 - shutter
    "\U0000e93f", # 30 - shutter
    "\U0000e940", # 40 - shutter
    "\U0000e941", # 50 - shutter
    "\U0000e93c", # 60 - shutter
    "\U0000e943", # 70 - shutter
    "\U0000e944", # 80 - shutter
    "\U0000e942", # 90 - shutter
    "\U0000e91e"  # 100 - shutter_open
  ]

- file: "fonts/materialdesignicons-webfont.ttf"
  id: mdi_icons_24
  size: 24
  bpp: 4
  glyphs: [
    "\U000F0210", # fan
    "\U000F068A", # shield home
    "\U000F1828", # shield moon
    "\U000F099D", # shield lock
    "\U000F06BB", # shield plane
    "\U000F099E", # shield off
    "\U000F0498", # shield
  ]


- file: "fonts/materialdesignicons-webfont.ttf"
  id: mdi_icons_28
  size: 28
  bpp: 4
  glyphs: [
    "\U000F0238", # heat
    "\U000F0717", # cool
    "\U000F0210", # fan
    "\U000F1B18", # auto
    "\U000F0425", # off
  ]


- file: "fonts/materialdesignicons-webfont.ttf"
  id: mdi_icons_40
  size: 40
  bpp: 4
  glyphs: [
    "\U000F068A", # shield home
    "\U000F1828", # shield moon
    "\U000F099D", # shield lock
    "\U000F06BB", # shield plane
    "\U000F099E", # shield off
    "\U000F0498", # shield
  ]

- file: "fonts/materialdesignicons-webfont.ttf"
  id: mdi_icons_52
  size: 52
  bpp: 4
  glyphs: [
    "\U000F068A", # shield home
    "\U000F1828", # shield moon
    "\U000F099D", # shield lock
    "\U000F06BB", # shield plane
    "\U000F099E", # shield off
    "\U000F0498", # shield
    "\U000F0826", # home
    "\U000F1A46", # away
  ]

- file: "fonts/materialdesignicons-webfont.ttf"
  id: mdi_icons_68
  size: 68
  bpp: 4
  glyphs: [
    "\U000F068A", # shield home
    "\U000F1828", # shield moon
    "\U000F099D", # shield lock
    "\U000F06BB", # shield plane
    "\U000F099E", # shield off
    "\U000F0498", # shield
  ]

- file: "fonts/materialdesignicons-webfont.ttf"
  id: mdi_icons_72
  size: 72
  bpp: 4
  glyphs: [
    "\U000F099D", # shield lock
  ]