  #############################
  ########### LOGO ############
  #############################

- file: 'img/loading/homeassistant.png'
  id: ha_img
  type: rgb565
  resize: 400x82
  transparency: alpha_channel

- file: 'img/loading/esphome.png'
  id: esphome_img
  type: rgb565
  resize: 320x95
  transparency: alpha_channel

  #############################
  ########## LIGHT ############
  ############################# 

- file: 'img/light/lightbulb.png'
  id: lightbulb_image
  type: rgb565
  transparency: alpha_channel

- file: 'img/light/rgb_ring.png'
  id: rgb_img
  type: rgb565
  transparency: alpha_channel

  #############################
  ########## VACUUM ###########
  #############################

- file: 'img/vacuum/vacuum.png'
  id: vacuum_img
  type: rgb565
  resize: 200x200
  transparency: alpha_channel

- file: 'img/vacuum/vacuum_0_10.png'
  id: vacuum_0_10_img
  type: rgb565
  resize: 200x200
  transparency: alpha_channel

- file: 'img/vacuum/vacuum_0_20.png'
  id: vacuum_0_20_img
  type: rgb565
  resize: 200x200
  transparency: alpha_channel

- file: 'img/vacuum/vacuum_0_30.png'
  id: vacuum_0_30_img
  type: rgb565
  resize: 200x200
  transparency: alpha_channel

- file: 'img/vacuum/vacuum_5.png'
  id: vacuum_5_img
  type: rgb565
  resize: 200x200
  transparency: alpha_channel

- file: 'img/vacuum/vacuum_10.png'
  id: vacuum_10_img
  type: rgb565
  resize: 200x200
  transparency: alpha_channel

- file: 'img/vacuum/vacuum_15.png'
  id: vacuum_15_img
  type: rgb565
  resize: 200x200
  transparency: alpha_channel

- file: 'img/vacuum/vacuum_20.png'
  id: vacuum_20_img
  type: rgb565
  resize: 200x200
  transparency: alpha_channel

- file: 'img/vacuum/vacuum_20_10.png'
  id: vacuum_20_10_img
  type: rgb565
  resize: 200x200
  transparency: alpha_channel

- file: 'img/vacuum/vacuum_20_20.png'
  id: vacuum_20_20_img
  type: rgb565
  resize: 200x200
  transparency: alpha_channel

- file: 'img/vacuum/vacuum_20_30.png'
  id: vacuum_20_30_img
  type: rgb565
  resize: 200x200
  transparency: alpha_channel

- file: 'img/vacuum/vacuum_355.png'
  id: vacuum_355_img
  type: rgb565
  resize: 200x200
  transparency: alpha_channel

- file: 'img/vacuum/vacuum_350.png'
  id: vacuum_350_img
  type: rgb565
  resize: 200x200
  transparency: alpha_channel

- file: 'img/vacuum/vacuum_345.png'
  id: vacuum_345_img
  type: rgb565
  resize: 200x200
  transparency: alpha_channel

- file: 'img/vacuum/vacuum_340.png'
  id: vacuum_340_img
  type: rgb565
  resize: 200x200
  transparency: alpha_channel

- file: 'img/vacuum/vacuum_340_10.png'
  id: vacuum_340_10_img
  type: rgb565
  resize: 200x200
  transparency: alpha_channel

- file: 'img/vacuum/vacuum_340_20.png'
  id: vacuum_340_20_img
  type: rgb565
  resize: 200x200
  transparency: alpha_channel

- file: 'img/vacuum/vacuum_340_30.png'
  id: vacuum_340_30_img
  type: rgb565
  resize: 200x200
  transparency: alpha_channel

  #############################
  ########## WEATHER ##########
  #############################

- file: 'img/weather/sunny.png'
  id: sunny_img
  type: rgb565
  resize: 100x100
  transparency: alpha_channel

- file: 'img/weather/clear_night.png'
  id: clear_night_img
  type: rgb565
  resize: 100x100
  transparency: alpha_channel

- file: 'img/weather/cloudy.png'
  id: cloudy_img
  type: rgb565
  resize: 100x100
  transparency: alpha_channel

- file: 'img/weather/partlycloudy_sun.png'
  id: partlycloudy_sun_img
  type: rgb565
  resize: 100x100
  transparency: alpha_channel

- file: 'img/weather/partlycloudy_moon.png'
  id: partlycloudy_moon_img
  type: rgb565
  resize: 100x100
  transparency: alpha_channel

- file: 'img/weather/rainy.png'
  id: rainy_img
  type: rgb565
  resize: 100x100
  transparency: alpha_channel

- file: 'img/weather/pouring.png'
  id: pouring_img
  type: rgb565
  resize: 100x100
  transparency: alpha_channel

- file: 'img/weather/snowy.png'
  id: snowy_img
  type: rgb565
  resize: 100x100
  transparency: alpha_channel

- file: 'img/weather/snowy_rainy.png'
  id: snowy_rainy_img
  type: rgb565
  resize: 100x100
  transparency: alpha_channel

- file: 'img/weather/fog.png'
  id: fog_img
  type: rgb565
  resize: 100x100
  transparency: alpha_channel

- file: 'img/weather/hail.png'
  id: hail_img
  type: rgb565
  resize: 100x100
  transparency: alpha_channel

- file: 'img/weather/lightning.png'
  id: lightning_img
  type: rgb565
  resize: 100x100
  transparency: alpha_channel

- file: 'img/weather/lightning_rainy.png'
  id: lightning_rainy_img
  type: rgb565
  resize: 100x100
  transparency: alpha_channel

- file: 'img/weather/windy.png'
  id: windy_img
  type: rgb565
  resize: 100x100
  transparency: alpha_channel

- file: 'img/weather/windy_variant.png'
  id: windy_variant_img
  type: rgb565
  resize: 100x100
  transparency: alpha_channel

  #############################
  ########## FLAGS ############
  #############################

- file: 'img/flags/de.png'
  id: flags_de_img
  type: rgb565
  resize: 60x80
  transparency: alpha_channel

- file: 'img/flags/es.png'
  id: flags_es_img
  type: rgb565
  resize: 60x80
  transparency: alpha_channel

- file: 'img/flags/fr.png'
  id: flags_fr_img
  type: rgb565
  resize: 60x80
  transparency: alpha_channel

- file: 'img/flags/gb.png'
  id: flags_gb_img
  type: rgb565
  resize: 60x80
  transparency: alpha_channel

- file: 'img/flags/it.png'
  id: flags_it_img
  type: rgb565
  resize: 60x80
  transparency: alpha_channel

- file: 'img/flags/kr.png'
  id: flags_kr_img
  type: rgb565
  resize: 60x80
  transparency: alpha_channel

- file: 'img/flags/pt.png'
  id: flags_pt_img
  type: rgb565
  resize: 60x80
  transparency: alpha_channel

- file: 'img/flags/ru.png'
  id: flags_ru_img
  type: rgb565
  resize: 60x80
  transparency: alpha_channel

- file: 'img/flags/us.png'
  id: flags_us_img
  type: rgb565
  resize: 60x80
  transparency: alpha_channel

- file: 'img/flags/pl.png'
  id: flags_pl_img
  type: rgb565
  resize: 60x80
  transparency: alpha_channel

- file: 'img/flags/tr.png'
  id: flags_tr_img
  type: rgb565
  resize: 60x80
  transparency: alpha_channel

- file: 'img/flags/sv.png'
  id: flags_sv_img
  type: rgb565
  resize: 60x80
  transparency: alpha_channel

- file: 'img/flags/id.png'
  id: flags_id_img
  type: rgb565
  resize: 60x80
  transparency: alpha_channel

- file: 'img/flags/vi.png'
  id: flags_vi_img
  type: rgb565
  resize: 60x80
  transparency: alpha_channel

- file: 'img/flags/ro.png'
  id: flags_ro_img
  type: rgb565
  resize: 60x80
  transparency: alpha_channel

- file: 'img/flags/nl.png'
  id: flags_nl_img
  type: rgb565
  resize: 60x80
  transparency: alpha_channel

- file: 'img/flags/hu.png'
  id: flags_hu_img
  type: rgb565
  resize: 60x80
  transparency: alpha_channel

- file: 'img/flags/cs.png'
  id: flags_cs_img
  type: rgb565
  resize: 60x80
  transparency: alpha_channel

- file: 'img/flags/fi.png'
  id: flags_fi_img
  type: rgb565
  resize: 60x80
  transparency: alpha_channel

- file: 'img/flags/ua.png'
  id: flags_ua_img
  type: rgb565
  resize: 60x80
  transparency: alpha_channel

  #############################
  ########## BATTERY ##########
  #############################

- file: 'img/battery/battery_very_high.png'
  id: battery_very_high_img
  type: rgb565
  transparency: alpha_channel

- file: 'img/battery/battery_high.png'
  id: battery_high_img
  type: rgb565
  transparency: alpha_channel

- file: 'img/battery/battery_middle.png'
  id: battery_middle_img
  type: rgb565
  transparency: alpha_channel

- file: 'img/battery/battery_low.png'
  id: battery_low_img
  type: rgb565
  transparency: alpha_channel

- file: 'img/battery/battery_very_low.png'
  id: battery_very_low_img
  type: rgb565
  transparency: alpha_channel

- file: 'img/battery/battery_empty.png'
  id: battery_empty_img
  type: rgb565
  transparency: alpha_channel

- file: 'img/battery/battery_80.png'
  id: battery_80_img
  type: rgb565
  transparency: alpha_channel

- file: 'img/battery/battery_60.png'
  id: battery_60_img
  type: rgb565
  transparency: alpha_channel

- file: 'img/battery/battery_40.png'
  id: battery_40_img
  type: rgb565
  transparency: alpha_channel

- file: 'img/battery/battery_20.png'
  id: battery_20_img
  type: rgb565
  transparency: alpha_channel

- file: 'img/battery/battery_0.png'
  id: battery_0_img
  type: rgb565
  transparency: alpha_channel

  #############################
  ########## PLAYER ###########
  #############################

# - file: 'img/player/Nashe radio.png'
#   id: nashe_img
#   type: rgb565
#   transparency: alpha_channel

# - file: 'img/player/radio-bayraktar.png'
#   id: bayraktar_img
#   type: rgb565
#   transparency: alpha_channel

# - file: 'img/player/RzK.png'
#   id: rzk_img
#   type: rgb565
#   transparency: alpha_channel


