text_sensor:
  - platform: homeassistant
    id: ${widget_name}_light_rgb_state
    entity_id: "${light_entity}"
    on_value:

      - if:
          condition:
            lambda: 'return x == "on";'
          then:
            - lvgl.label.update:
                id: ${widget_name}_light_on
                text_color: color_amber
          else:
            - lvgl.label.update:
                id: ${widget_name}_light_on
                text_color: color_steel_blue

